contact_links:
  - name: ğŸ’¡ Feature Request
    url: https://github.com/ptarmiganlabs/butler-spyglass/discussions/new
    about: Share ideas for new features
  - name: â“ Question
    url: https://github.com/ptarmiganlabs/butler-spyglass/discussions/new
    about: General questions